# Generated by Django 4.2.6 on 2024-03-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_reminder", "0002_medicine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicine",
            old_name="form",
            new_name="medicine_form",
        ),
        migrations.RenameField(
            model_name="medicine",
            old_name="frequency",
            new_name="medicine_frequency",
        ),
        migrations.RenameField(
            model_name="medicine",
            old_name="name",
            new_name="medicine_name",
        ),
        migrations.RenameField(
            model_name="medicine",
            old_name="strength",
            new_name="medicine_strength",
        ),
        migrations.RenameField(
            model_name="medicine",
            old_name="unit",
            new_name="medicine_unit",
        ),
    ]
