# Generated by Django 4.2.6 on 2024-03-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_reminder", "0004_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.CharField(blank=True, max_length=2050, null=True),
        ),
    ]
